export const sliderItems = [
  {
    id: 1,
    img: "https://cdn.pixabay.com/photo/2015/09/06/00/12/model-926528_960_720.jpg",
    title: "Summer Sale",
    desc: "Get flat 30% of new arrivales!",
    bg: "#f5fafd",
  },
  {
    id: 2,
    img: "https://cdn.pixabay.com/photo/2021/01/02/17/24/rear-5882411_960_720.jpg",
    title: "Popular Sale",
    desc: "Get flat 30% of new arrivales!",
    bg: "#fcf1ed",
  },
  {
    id: 3,
    img: "https://cdn.pixabay.com/photo/2017/04/04/10/37/girl-2200984_960_720.jpg",
    title: "Summer Sale",
    desc: "Get flat 30% of new arrivales!",
    bg: "#fbf0f4",
  },
];

export const categories = [
  {
    id: 1,
    img: "https://cdn.pixabay.com/photo/2016/03/23/21/03/smile-1275668_960_720.jpg",
    imgSmall: "https://cdn.pixabay.com/photo/2016/04/01/00/35/shoes-1298268_960_720.jpg",
    title: "Women",
  },
  {
    id: 2,
    img: "https://cdn.pixabay.com/photo/2016/11/29/01/34/man-1866572_960_720.jpg",
    imgSmall: "https://cdn.pixabay.com/photo/2015/01/16/15/01/fashion-601553_960_720.jpg",
    title: "Men",
  },
  {
    id: 3,
    img: "https://cdn.pixabay.com/photo/2021/03/21/13/32/kids-6112105_960_720.jpg",
    imgSmall: "https://cdn.pixabay.com/photo/2021/06/17/18/28/childhood-friends-6344306_960_720.jpg",
    title: "Kids",
  },
];

export const products = [
  {
    id: 1,
    img: "https://cdn.pixabay.com/photo/2017/08/08/00/23/woman-2609573_960_720.jpg",
    category: "Women",
    title: "Jeans",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 20,
    favorite: false,
    color: ["red", "blue", "yellow", "green"],
    size: ["S", "M", "XL"],
    count: 0,
    newest: false,
  },
  {
    id: 2,
    img: "https://cdn.pixabay.com/photo/2013/07/12/18/20/shoes-153310_960_720.png",
    category: "Women",
    title: "Keds",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 15,
    favorite: false,
    color: ["black", "red", "blue", "yellow"],
    size: ["S", "M", "XL"],
    count: 0,
    newest: false,
  },
  {
    id: 3,
    img: "https://cdn.pixabay.com/photo/2017/09/01/21/53/sunglasses-2705642_960_720.jpg",
    category: "Women",
    title: "Glasses",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 5,
    favorite: false,
    color: ["grey", "red", "blue", "yellow", "green"],
    size: ["S", "M", "L"],
    count: 0,
    newest: false,
  },
  {
    id: 4,
    img: "https://cdn.pixabay.com/photo/2013/11/14/12/34/neckties-210347_960_720.jpg",
    category: "Women",
    title: "Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 10,
    favorite: false,
    color: ["grey", "blue", "yellow", "green"],
    size: ["S", "M", "XL"],
    count: 0,
    newest: false,
  },
  {
    id: 5,
    img: "https://cdn.pixabay.com/photo/2016/11/22/19/08/hangers-1850082_960_720.jpg",
    category: "Women",
    title: "Dress",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 12,
    favorite: false,
    color: ["grey", "black", "red", "blue", "yellow", "green"],
    size: ["XS", "S", "M", "L"],
    count: 0,
    newest: false,
  },
  {
    id: 6,
    img: "https://cdn.pixabay.com/photo/2016/03/27/19/31/fashion-1283863_960_720.jpg",
    category: "Women",
    title: "Sweater",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 16,
    favorite: false,
    color: ["grey", "black", "red", "green"],
    size: ["S", "M"],
    count: 0,
    newest: false,
  },
  {
    id: 7,
    img: "https://cdn.pixabay.com/photo/2018/12/05/13/41/woman-3857758_960_720.jpg",
    category: "Women",
    title: "Pants",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 18,
    favorite: false,
    color: ["grey", "black", "red", "blue", "green"],
    size: ["S", "M", "L", "XL"],
    count: 0,
    newest: false,
  },
  {
    id: 8,
    img: "https://cdn.pixabay.com/photo/2014/08/26/21/48/sweatshirts-428607_960_720.jpg",
    category: "Women",
    title: "Hoodie",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 25,
    favorite: false,
    color: ["grey", "black", "red", "blue", "yellow", "green"],
    size: ["S", "M", "L", "XL"],
    count: 0,
    newest: false,
  },
  {
    id: 9,
    img: "https://cdn.pixabay.com/photo/2017/08/17/08/20/online-shopping-2650383_960_720.jpg",
    category: "Women",
    title: "Handbag",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 22,
    favorite: false,
    color: ["grey", "red", "blue", "green"],
    size: ["S", "M"],
    count: 0,
    newest: false,
  },
  {
    id: 10,
    img: "https://cdn.pixabay.com/photo/2019/03/12/13/26/jeans-4050815_960_720.jpg",
    category: "Men",
    title: "Jeans",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 15,
    favorite: false,
    color: ["yellow", "green"],
    size: ["XS", "S", "M"],
    count: 0,
    newest: false,
  },
  {
    id: 11,
    img: "https://cdn.pixabay.com/photo/2015/01/16/15/01/fashion-601565_960_720.jpg",
    category: "Men",
    title: "Boots",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 30,
    favorite: false,
    color: ["grey", "black", "yellow"],
    size: ["S", "M", "L"],
    count: 0,
    newest: false,
  },
  {
    id: 12,
    img: "https://cdn.pixabay.com/photo/2017/08/27/05/33/trousers-2685231_960_720.jpg",
    category: "Men",
    title: "Trousers",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 24,
    favorite: false,
    color: ["grey", "black", "red", "blue", "yellow", "green"],
    size: ["S", "M", "L"],
    count: 0,
    newest: false,
  },
  {
    id: 13,
    img: "https://cdn.pixabay.com/photo/2015/09/23/03/07/menswear-952835_960_720.jpg",
    category: "Men",
    title: "Trousers Belt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 12,
    favorite: false,
    color: ["grey", "red", "yellow", "green"],
    size: ["S", "M", "L"],
    count: 0,
    newest: false,
  },
  {
    id: 14,
    img: "https://cdn.pixabay.com/photo/2015/09/11/21/58/red-bow-tie-936466_960_720.jpg",
    category: "Men",
    title: "Bow Tie",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 6,
    favorite: false,
    color: ["black", "red", "blue", "yellow"],
    size: ["S", "M", "XL"],
    count: 0,
    newest: false,
  },
  {
    id: 15,
    img: "https://cdn.pixabay.com/photo/2014/11/14/19/57/sneakers-531172_960_720.jpg",
    category: "Men",
    title: "Keds",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 20,
    favorite: false,
    color: ["grey", "black", "blue", "yellow", "green"],
    size: ["XS", "S", "M", "XL"],
    count: 0,
    newest: false,
  },
  {
    id: 16,
    img: "https://cdn.pixabay.com/photo/2018/05/26/14/11/hat-3431418_960_720.jpg",
    category: "Men",
    title: "Hats",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 4,
    favorite: false,
    color: ["grey", "black", "yellow", "green"],
    size: ["S", "M", "L"],
    count: 0,
    newest: true,
  },
  {
    id: 17,
    img: "https://cdn.pixabay.com/photo/2018/10/10/14/24/shirt-3737405_960_720.jpg",
    category: "Men",
    title: "Jacket",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 35,
    favorite: false,
    color: ["grey", "black", "red", "blue", "yellow", "green"],
    size: ["S", "M", "XL"],
    count: 0,
    newest: false,
  },
  {
    id: 18,
    img: "https://cdn.pixabay.com/photo/2016/12/06/09/31/blank-1886008_960_720.png",
    category: "Men",
    title: "T-shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 8,
    favorite: false,
    color: ["grey", "green"],
    size: ["XS", "S", "M"],
    count: 0,
    newest: false,
  },
  {
    id: 19,
    img: "https://cdn.pixabay.com/photo/2018/12/17/23/39/baby-shoes-3881526_960_720.jpg",
    category: "Kids",
    title: "Boots",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 10,
    favorite: false,
    color: ["black", "yellow"],
    size: ["S", "M", "L"],
    count: 0,
    newest: true,
  },
  {
    id: 20,
    img: "https://cdn.pixabay.com/photo/2018/11/05/10/23/children-dresses-3795739_960_720.jpg",
    category: "Kids",
    title: "Jacket",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 15,
    favorite: false,
    color: ["grey", "black", "red", "blue", "yellow", "green"],
    size: ["S", "M"],
    count: 0,
    newest: false,
  },
  {
    id: 21,
    img: "https://cdn.pixabay.com/photo/2018/08/07/19/39/childrens-photo-shoot-3590536_960_720.jpg",
    category: "Kids",
    title: "Hat",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 8,
    favorite: false,
    color: ["grey", "black", "red", "yellow", "green"],
    size: ["S", "M"],
    count: 0,
    newest: false,
  },
  {
    id: 22,
    img: "https://cdn.pixabay.com/photo/2018/08/23/17/59/boy-3626334_960_720.jpg",
    category: "Kids",
    title: "Umbrella",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 5,
    favorite: false,
    color: ["grey", "black", "red", "blue", "green"],
    size: ["S", "M", "XL"],
    count: 0,
    newest: false,
  },
  {
    id: 23,
    img: "https://cdn.pixabay.com/photo/2018/09/23/12/43/dresses-3697374_960_720.jpg",
    category: "Kids",
    title: "Dress",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 9,
    favorite: false,
    color: ["green"],
    size: ["S", "M", "XL"],
    count: 0,
    newest: true,
  },
  {
    id: 24,
    img: "https://cdn.pixabay.com/photo/2018/04/20/16/54/children-model-3336530_960_720.jpg",
    category: "Kids",
    title: "Scarf",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 7,
    favorite: false,
    color: ["grey", "black", "red", "blue", "yellow", "green"],
    size: ["XS", "S", "M"],
    count: 0,
    newest: false,
  },
  {
    id: 25,
    img: "https://cdn.pixabay.com/photo/2018/01/10/23/43/childrens-shoes-3075082_960_720.png",
    category: "Kids",
    title: "Keds",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 14,
    favorite: false,
    color: ["grey", "yellow", "green"],
    size: ["S", "M", "L"],
    count: 0,
    newest: false,
  },
  {
    id: 26,
    img: "https://cdn.pixabay.com/photo/2021/05/24/12/46/kids-6279080_960_720.jpg",
    category: "Kids",
    title: "Sunglasses",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 3,
    favorite: false,
    color: ["grey", "black", "green"],
    size: ["S", "M"],
    count: 0,
    newest: true,
  },
  {
    id: 27,
    img: "https://cdn.pixabay.com/photo/2017/09/02/19/12/childrens-fashion-2708238_960_720.jpg",
    category: "Kids",
    title: "T-shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 6,
    favorite: false,
    color: ["grey", "blue", "yellow", "green"],
    size: ["S", "M"],
    count: 0,
    newest: false,
  },
  {
    id: 28,
    img: "https://cdn.pixabay.com/photo/2017/11/18/06/47/boy-2959305_960_720.jpg",
    category: "Jacket",
    title: "Jeans",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Natus, repudiandae accusantium maiores veritatis quas nostrum sequi odit facilis quia quod vero sed cum ipsam illum voluptatum. Suscipit ipsa officiis tempore?",
    price: 16,
    favorite: false,
    color: ["grey"],
    size: ["S", "M"],
    count: 0,
    newest: false,
  },
];
